on:
  push:
    tags:
    - 'v[0-9]+\.[0-9]+\.[0-9]+' 

name: Create Release and Upload Assets

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Get bare tag
        id: baretag
        run: echo "::set-output name=baretag::$(echo ${{ github.ref }} | cut -b 12-)
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          TAGVER=${{ steps.baretag.outputs.baretag }} make release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.baretag.outputs.baretag }} / ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
      - name: Upload Release Asset (linux-amd64)
        id: upload-release-asset-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./OPATH/mockster-${{ steps.baretag.outputs.baretag }}.linux-amd64.tar.gz
          asset_name: mockster-${{ steps.baretag.outputs.baretag }}.linux-amd64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Release Asset (linux-arm64)
        id: upload-release-asset-linux-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./OPATH/mockster-${{ steps.baretag.outputs.baretag }}.linux-arm64.tar.gz
          asset_name: mockster-${{ steps.baretag.outputs.baretag }}.linux-arm64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Release Asset (darwin-amd64)
        id: upload-release-asset-darwin-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./OPATH/mockster-${{ steps.baretag.outputs.baretag }}.darwin-amd64.tar.gz
          asset_name: mockster-${{ steps.baretag.outputs.baretag }}.darwin-amd64.tar.gz
          asset_content_type: application/gzip
      - name: Upload Release Asset (windows-amd64)
        id: upload-release-asset-windows-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./OPATH/mockster-${{ steps.baretag.outputs.baretag }}.windows-amd64.tar.gz
          asset_name: mockster-${{ steps.baretag.outputs.baretag }}.windows-amd64.tar.gz
          asset_content_type: application/gzip
